# Generated by Django 5.2.5 on 2025-09-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_alter_employee_user_leave'),
        ('masters', '0002_usercustom_performancekpi_max_score'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('contract', 'Contract'), ('intern', 'Internship'), ('part_time', 'Part-time')], default='full_time', max_length=20)),
                ('experience_min', models.PositiveIntegerField(blank=True, help_text='Years', null=True)),
                ('experience_max', models.PositiveIntegerField(blank=True, help_text='Years', null=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Annual INR', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Annual INR', null=True)),
                ('reason_for_hire', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True, help_text='Comma separated or free text')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('filled', 'Filled')], default='draft', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.usercustom')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management.department')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.usercustom')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills (e.g., Python, Django, React)', null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('experience', models.DecimalField(decimal_places=1, help_text='Years of experience', max_digits=4)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='applied', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobrequisition')),
            ],
        ),
    ]
