# Generated by Django 5.2.5 on 2025-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_jobrequisition_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
