# Generated by Django 5.2.5 on 2025-09-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_jobrequisition_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('hired', 'Hired')], default='applied', max_length=20),
        ),
    ]
