# Generated by Django 4.2.25 on 2025-11-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_remove_employee_user_alter_leave_leave_type'),
        ('masters', '0005_usercustom_is_locked_usercustom_passcode_and_more'),
        ('recruitment', '0004_alter_applicant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequisition',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='reason_for_hire',
        ),
        migrations.AddField(
            model_name='applicant',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='compensation_benefits',
            field=models.TextField(blank=True, help_text='Describe perks: health insurance, bonuses, PF, ESOPs, etc.'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='job_id',
            field=models.CharField(default=1, editable=False, help_text='Auto-generated ID like 0001', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='overview',
            field=models.TextField(blank=True, help_text='Short description or reason for hire'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='work_mode',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('remote', 'Remote / Work from Home'), ('flexible', 'Flexible / Offset')], default='onsite', help_text='Select the work mode: Onsite, Hybrid, Remote, or Flexible', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Years of experience', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Internship')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.usercustom'),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('on_hold', 'On Hold'), ('rejected', 'Rejected'), ('filled', 'Filled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ResumeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employee')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobrequisition')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='recruitment.resumesubmission'),
        ),
    ]
