# Generated by Django 4.2.23 on 2025-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0002_employee_salarydeclaration_salaryslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydeclaration',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='tax',
        ),
        migrations.AddField(
            model_name='payroll',
            name='days_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='lwf_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='lwop_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pf_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='SalaryDeclaration',
        ),
        migrations.DeleteModel(
            name='SalarySlip',
        ),
    ]
