# Generated by Django 5.2.5 on 2025-09-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_remove_employee_salary_employee_branch_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave / Medical Leave'), ('ML', 'Maternity Leave'), ('PL', 'Paternity Leave'), ('BL', 'Bereavement / Compassionate Leave'), ('Marriage', 'Marriage Leave'), ('Sabbatical', 'Sabbatical / Study Leave'), ('Optional', 'Optional / Privilege Holiday'), ('CO', 'Compensatory Off / Comp Off'), ('Volunteer', 'Volunteer / CSR Leave'), ('WFH', 'Work From Home Days'), ('Adoption', 'Adoption Leave'), ('Special', 'Special Leave / Festival Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('admin_reason', models.TextField(blank=True, null=True)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('next_working_day', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employee_management.employee')),
            ],
            options={
                'db_table': 'employee_management_leave',
                'ordering': ['-applied_on'],
            },
        ),
    ]
