# Generated by Django 4.2.25 on 2025-11-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_usercustom_is_locked_usercustom_passcode_and_more'),
        ('employee_management', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.leavetype'),
        ),
    ]
