# Generated by Django 5.2.5 on 2025-09-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_usercustom_performancekpi_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancekpi',
            name='goal_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum score required to mark this goal as achieved', max_digits=5),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='review_frequency_days',
            field=models.IntegerField(default=90, help_text='Number of days after which review is due'),
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('viewed', 'Viewed')], max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='masters.usercustom')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
