# Generated by Django 5.2.5 on 2025-09-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('masters', '0003_performancekpi_goal_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='user_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='user_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
