# Generated by Django 4.2.25 on 2025-11-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_remove_recentactivity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='passcode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='passcode_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='wrong_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
