# Generated by Django 5.2.5 on 2025-09-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_usercustom_performancekpi_max_score'),
        ('performance_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='score',
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.performancekpi')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='performance_management.performancereview')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback360',
        ),
    ]
